#@copyright : abdo azz
CC=arm-none-eabi-
CFLAGS=-g -mcpu=arm926ej-s
INCS=-I.
LIBS=
SRC= $(wildcard *.c)
OBJ=$(SRC:.c=.o)
AS= $(wildcard *.s)
ASOBJ=$(AS:.s=.o)
Project_name=Abdo
all:$(Project_name).bin
	@echo "=====Build done======="
startup.o : startup.s
	$(CC)as.exe $(CFLAGS) $< -o $@

%.o:%.c
	$(CC)gcc.exe -c $(INCS) $(CFLAGS) $< -o $@

$(Project_name).elf: $(OBJ) $(ASOBJ) 
	$(CC)ld.exe -T linker_all.ld $(LIBS) $(OBJ) $(ASOBJ) -o $(Project_name).elf

$(Project_name).bin: $(Project_name).elf
	$(CC)objcopy.exe -O binary $< $@
clean:
	rm *.o *.elf
clean_all: 
	rm *.o *.bin *.elf
 
