#@copyright : abdo azz
CC=arm-none-eabi-
CFLAGS=-g -mcpu=cortex-m3 -gdwarf-2
INCS=-I .
LIBS=
SRC= $(wildcard *.c)
OBJ=$(SRC:.c=.o)
AS= $(wildcard *.s)
ASOBJ=$(AS:.s=.o)
Project_name=cortex-m3
all:$(Project_name).bin
	@echo "=====Build done======="
startup.o : startup.s
	$(CC)as.exe $(CFLAGS) $< -o $@

%.o:%.c
	$(CC)gcc.exe -c $(INCS) $(CFLAGS) $< -o $@

$(Project_name).elf: $(OBJ) $(ASOBJ) 
	$(CC)ld.exe -T linker.ld $(LIBS) $(OBJ) $(ASOBJ) -o  $@ -Map=Mapfile.map 

$(Project_name).bin: $(Project_name).elf
	$(CC)objcopy.exe -O binary $< $@
clean:
	rm *.o *.elf
clean_all: 
	rm *.o *.bin *.elf
 
